# Generated by Django 2.0.2 on 2018-02-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_fist',
            field=models.BooleanField(default=False),
        ),
    ]
