# Generated by Django 2.0.2 on 2018-02-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_tracker_app', '0002_location_is_fist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='is_fist',
            new_name='is_first',
        ),
    ]
